import type { PlayerCharacter } from '@/entities/character';

export const MOCK_CHARACTERS: PlayerCharacter[] = [
  {
    id: 'char-alvin',
    campaignId: 'campaign-farchester',
    userId: 'user-ivan',
    name: 'Alvin Hart',
    gender: 'male',
    age: 24,
    species: 'Human',
    speciesId: 'species-human',
    gmNotes: '',
    groupMemberships: [],
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'char-godrik',
    campaignId: 'campaign-farchester',
    userId: 'user-seva',
    name: 'Godrik',
    gender: 'male',
    age: 31,
    species: 'Human',
    speciesId: 'species-human',
    class: 'Paladin',
    gmNotes: '',
    groupMemberships: [],
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'char-evelina',
    campaignId: 'campaign-farchester',
    userId: 'user-elya',
    name: 'Evelina',
    gender: 'female',
    age: 28,
    species: 'Halfling',
    speciesId: 'species-halfling',
    gmNotes: '',
    groupMemberships: [],
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'char-esme',
    campaignId: 'campaign-farchester',
    userId: 'user-zhenya',
    name: 'Esme',
    gender: 'female',
    age: 147,
    species: 'Elf',
    speciesId: 'species-elf',
    class: 'Alchemist',
    gmNotes: '',
    groupMemberships: [],
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'char-yanko',
    campaignId: 'campaign-farchester',
    userId: 'user-sergey',
    name: 'Yanko',
    gender: 'male',
    age: 27,
    class: 'Ranger',
    gmNotes: '',
    groupMemberships: [],
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'char-korvin',
    campaignId: 'campaign-drakkenheim',
    userId: 'user-ivan',
    name: 'Korvin',
    gender: 'male',
    age: 22,
    species: 'Human',
    speciesId: 'species-human',
    class: 'Wizard',
    gmNotes: '',
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'char-vermira',
    campaignId: 'campaign-drakkenheim',
    userId: 'user-adel',
    name: 'Vermira',
    gender: 'female',
    age: 68,
    species: 'Dwarf',
    speciesId: 'species-dwarf',
    class: 'Paladin',
    gmNotes: '',
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'char-sai',
    campaignId: 'campaign-drakkenheim',
    userId: 'user-natasha',
    name: 'Sai',
    gender: 'nonbinary',
    age: 194,
    species: 'Elf',
    speciesId: 'species-elf',
    gmNotes: '',
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'char-patrikeyevna',
    campaignId: 'campaign-drakkenheim',
    userId: 'user-jess',
    name: 'Patrikeyevna',
    gender: 'female',
    age: 35,
    class: 'Monk',
    gmNotes: '',
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
  },
];
