import type { PlayerCharacter } from '@/entities/character';

export const MOCK_CHARACTERS: PlayerCharacter[] = [
  {
    id: 'char-alvin',
    campaignId: 'campaign-farchester',
    userId: 'user-ivan',
    name: 'Alvin Hart',
    species: 'Human',
    gmNotes: '',
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'char-godrik',
    campaignId: 'campaign-farchester',
    userId: 'user-seva',
    name: 'Godrik',
    species: 'Human',
    class: 'Paladin',
    gmNotes: '',
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'char-evelina',
    campaignId: 'campaign-farchester',
    userId: 'user-elya',
    name: 'Evelina',
    species: 'Halfling',
    gmNotes: '',
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'char-esme',
    campaignId: 'campaign-farchester',
    userId: 'user-zhenya',
    name: 'Esme',
    species: 'Elf',
    class: 'Alchemist',
    gmNotes: '',
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'char-yanko',
    campaignId: 'campaign-farchester',
    userId: 'user-sergey',
    name: 'Yanko',
    class: 'Ranger',
    gmNotes: '',
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'char-korvin',
    campaignId: 'campaign-drakkenheim',
    userId: 'user-ivan',
    name: 'Korvin',
    species: 'Human',
    class: 'Wizard',
    gmNotes: '',
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'char-vermira',
    campaignId: 'campaign-drakkenheim',
    userId: 'user-adel',
    name: 'Vermira',
    species: 'Dwarf',
    class: 'Paladin',
    gmNotes: '',
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'char-sai',
    campaignId: 'campaign-drakkenheim',
    userId: 'user-natasha',
    name: 'Sai',
    species: 'Elf',
    gmNotes: '',
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'char-patrikeyevna',
    campaignId: 'campaign-drakkenheim',
    userId: 'user-jess',
    name: 'Patrikeyevna',
    class: 'Monk',
    gmNotes: '',
    createdAt: '2025-09-01T00:00:00Z',
  },
];
