import type { Location } from '@/entities/location';

export const MOCK_LOCATIONS: Location[] = [
  // ── Farchester ──────────────────────────────────────────────────────────
  {
    id: 'loc-fc-farchester',
    campaignId: 'campaign-farchester',
    name: 'Фарчестер',
    aliases: ['Farchester'],
    type: 'settlement',
    description:
      'Бывший вольный город в Степной Марке. Два года назад назначен имперский маркграф Кронхейв. Осада с востока гоблинами (~1,5 года), сухой закон, комендантский час, нехватка еды и воды.',
    gmNotes: 'Город под давлением — важен для кампании. Следи за балансом сил между Кронхейвом и бургомистром.',
    createdAt: '2026-02-24T00:00:00Z',
  },
  {
    id: 'loc-fc-rathusha',
    campaignId: 'campaign-farchester',
    name: 'Ратуша',
    aliases: ['Town Hall'],
    type: 'building',
    subtype: 'government',
    parentLocationId: 'loc-fc-farchester',
    description: 'Центральная ратуша. Место встречи с бургомистром Стоунгривом. Рядом фонтан.',
    createdAt: '2026-02-24T00:00:00Z',
  },
  {
    id: 'loc-fc-residence',
    campaignId: 'campaign-farchester',
    name: 'Резиденция Кронхейва',
    aliases: ["Kronhev's Residence"],
    type: 'building',
    subtype: 'estate',
    parentLocationId: 'loc-fc-farchester',
    description: 'Большой дом с садом, много стражников в красном. Резиденция Лорд-Адмирала Кронхейва.',
    createdAt: '2026-02-24T00:00:00Z',
  },
  {
    id: 'loc-fc-tavern',
    campaignId: 'campaign-farchester',
    name: 'Таверна Ы Куру Айр',
    aliases: ['Y Kuru Ayr', 'The Tavern'],
    type: 'building',
    subtype: 'tavern',
    parentLocationId: 'loc-fc-farchester',
    description: 'Таверна, где остановилась партия. Тавернщик Йорверт. Место отдыха и планирования.',
    createdAt: '2026-02-24T00:00:00Z',
  },
  {
    id: 'loc-fc-tower',
    campaignId: 'campaign-farchester',
    name: 'Башня мага',
    aliases: ["Mage's Tower", "Tuts' Tower"],
    type: 'building',
    subtype: 'tower',
    parentLocationId: 'loc-fc-farchester',
    description: 'Башня городского мага Тутса. Потрёпанная, но функционирующая.',
    createdAt: '2026-02-24T00:00:00Z',
  },

  // ── Drakkenheim — Regions ────────────────────────────────────────────────
  {
    id: 'loc-dk-region',
    campaignId: 'campaign-drakkenheim',
    name: 'Drakkenheim Region',
    aliases: ['Регион Дракенхейма'],
    type: 'region',
    description:
      'Регион вокруг разрушенного Дракенхейма. Заражён делириумом. Искажённые мутанты бродят по руинам.',
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'loc-dk-emberwood-region',
    campaignId: 'campaign-drakkenheim',
    name: 'Emberwood Village Region',
    aliases: ['Регион Эмбервуда'],
    type: 'region',
    description: 'Регион вокруг Эмбервуда — относительно безопасная зона вдали от делириума.',
    createdAt: '2025-09-01T00:00:00Z',
  },

  // ── Drakkenheim — Emberwood Region ──────────────────────────────────────
  {
    id: 'loc-dk-road',
    campaignId: 'campaign-drakkenheim',
    name: 'Road to Emberwood',
    aliases: ['Дорога в Эмбервуд'],
    type: 'natural',
    subtype: 'road',
    parentLocationId: 'loc-dk-emberwood-region',
    description:
      'Дорога в Эмбервуд — место первой встречи с делириумом. Здесь Рикард Вос прикоснулся к осколку и превратился в монстра. Богдан сбежал по этой дороге.',
    createdAt: '2025-09-02T00:00:00Z',
  },
  {
    id: 'loc-dk-zoya-house',
    campaignId: 'campaign-drakkenheim',
    name: 'Zoya House',
    aliases: ['Домик Зои'],
    type: 'building',
    subtype: 'residence',
    parentLocationId: 'loc-dk-emberwood-region',
    description:
      'Небольшой домик отшельницы Зои за пределами деревни. Её не жалуют в Эмбервуде. Продаёт янтарные шарики, поклоняется Старым богам. Знает лечение от заражения делириумом через Иоганна Призроткача.',
    createdAt: '2025-11-07T00:00:00Z',
  },

  // ── Drakkenheim — Emberwood Village ─────────────────────────────────────
  {
    id: 'loc-dk-emberwood',
    campaignId: 'campaign-drakkenheim',
    name: 'Emberwood Village',
    aliases: ['Эмбервуд', 'Emberwood'],
    type: 'settlement',
    parentLocationId: 'loc-dk-emberwood-region',
    description: 'Стартовая деревня, база партии. В раздрае, но относительно безопасна.',
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'loc-dk-marketplace',
    campaignId: 'campaign-drakkenheim',
    name: 'Marketplace',
    aliases: ['Рынок в Эмбервуд', 'Emberwood City Centre'],
    type: 'district',
    subtype: 'market',
    parentLocationId: 'loc-dk-emberwood',
    description:
      'Рынок в центре Эмбервуда. Работает с 10 утра. Ночные торговцы: Эрен Марлоу (припасы), Алдор (магические предметы), Орсон Фейруэзер (делириум и контейнеры).',
    createdAt: '2025-09-09T00:00:00Z',
  },
  {
    id: 'loc-dk-bark',
    campaignId: 'campaign-drakkenheim',
    name: 'Bark and Buzzard',
    aliases: ['Коршун и Ищейка'],
    type: 'building',
    subtype: 'tavern',
    parentLocationId: 'loc-dk-emberwood',
    description: 'Рекомендованная таверна. Еда 1gp, домик 2gp за человека. Хозяйка — Карин Альсберг.',
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'loc-dk-skull',
    campaignId: 'campaign-drakkenheim',
    name: 'Skull and Sword Taphouse',
    aliases: ['Меч и Череп'],
    type: 'building',
    subtype: 'tavern',
    parentLocationId: 'loc-dk-emberwood',
    description: "Таверна Людей Королевы. Подозрительная атмосфера. Место для контактов с Queen's Men.",
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'loc-dk-red-lion',
    campaignId: 'campaign-drakkenheim',
    name: 'Red Lion Hotel',
    aliases: ['Красный Лев'],
    type: 'building',
    subtype: 'hotel',
    parentLocationId: 'loc-dk-emberwood',
    description:
      'Дорогущий люксовый отель. Ночь: 25gp, бутылка вина: 100gp. Владелец — Коста Ставрос (теперь мёртв). Река (Аметисты) проводит вечера в отдельной библиотеке.',
    createdAt: '2025-09-02T00:00:00Z',
  },
  {
    id: 'loc-dk-gilded-lily',
    campaignId: 'campaign-drakkenheim',
    name: 'Gilded Lily',
    aliases: ['Позолоченная Лилия'],
    type: 'building',
    subtype: 'tavern',
    parentLocationId: 'loc-dk-emberwood',
    description:
      'Приятная таверна с музыкальными вечерами. Грог 1gp. Открытый вечер Микра. Владелица — Мадам Рошель.',
    createdAt: '2025-11-18T00:00:00Z',
  },
  {
    id: 'loc-dk-smithy',
    campaignId: 'campaign-drakkenheim',
    name: 'Crowe and Sons Smithy',
    aliases: ['Кузня Кроу'],
    type: 'building',
    subtype: 'shop',
    parentLocationId: 'loc-dk-emberwood',
    description: 'Кузня Тобиаса Кроу. Дорогая, но делают на заказ.',
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'loc-dk-chapel',
    campaignId: 'campaign-drakkenheim',
    name: 'Chapel of Saint Ardenna',
    aliases: ['Часовня Святой Арденны'],
    type: 'building',
    subtype: 'temple',
    parentLocationId: 'loc-dk-emberwood',
    description: 'База Рыцарей Серебряного Ордена в Эмбервуде. Центр Священного Пламени.',
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'loc-dk-watchtower',
    campaignId: 'campaign-drakkenheim',
    name: 'Emberwood Watchtower',
    aliases: ['Часовая Башня', 'Башня фонарей'],
    type: 'building',
    subtype: 'military',
    parentLocationId: 'loc-dk-emberwood',
    description:
      'Башня Капюшонных Фонарей — самая высокая постройка в деревне. Охрана у моста, проверка на заражение делириумом. Капитан дозора — Рейн Хайлэш.',
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'loc-dk-old-rattlecan',
    campaignId: 'campaign-drakkenheim',
    name: 'Old Rattlecan',
    aliases: ['Старый Трещот'],
    type: 'building',
    subtype: 'curiosity',
    parentLocationId: 'loc-dk-emberwood',
    description:
      'Анимированные доспехи на заднем дворе "Коршуна и Ищейки". Местное развлечение. В сессии 3 местные полезли к нему — Патрикеевна получила по лицу. Кто его создал — неизвестно.',
    createdAt: '2025-09-23T00:00:00Z',
  },

  // ── Drakkenheim — Drakkenheim Region (outside city) ─────────────────────
  {
    id: 'loc-dk-eckerman-mill',
    campaignId: 'campaign-drakkenheim',
    name: 'Eckerman Mill',
    aliases: ['Мельница Эккермена'],
    type: 'building',
    subtype: 'mill',
    parentLocationId: 'loc-dk-region',
    description:
      'Мельница за пределами Дракенхейма и Эмбервуда. Река когда-то предлагала встретиться здесь. Рядом — заброшенный особняк, место встречи с подозрительной личностью, продающей заражённые зелья (квест Фонарей).',
    createdAt: '2025-11-07T00:00:00Z',
  },

  // ── Drakkenheim — Drakkenheim City ──────────────────────────────────────
  {
    id: 'loc-dk-city',
    campaignId: 'campaign-drakkenheim',
    name: 'Drakkenheim',
    aliases: ['Дракенхейм', 'Драккенхейм'],
    type: 'settlement',
    parentLocationId: 'loc-dk-region',
    description:
      'Разрушенный город. Место падения метеорита с делириумом. Крайне опасно: заражение, монстры, Искажённые. Река Дран — граница безопасной зоны.',
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'loc-dk-house-copperpot',
    campaignId: 'campaign-drakkenheim',
    name: "House with Copperpot's Corpse",
    aliases: ['Домик с трупом Копперпота'],
    type: 'building',
    subtype: 'ruin',
    parentLocationId: 'loc-dk-city',
    description:
      'Место в Дракенхейме с трупом Коксворда Б. Копперпота. Содержит: нерабочий круг телепортации, скрытую записку на неизвестном языке (не расшифрована), надпись на стене.',
    createdAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'loc-dk-champions-gate',
    campaignId: 'campaign-drakkenheim',
    name: "Champion's Gate",
    aliases: ['Врата Чемпионов'],
    type: 'building',
    subtype: 'gate',
    parentLocationId: 'loc-dk-city',
    description:
      "Врата в Дракенхейме — место тусовки культистов Падшего Пламени. Здесь обосновалась Лукреция Матиас.",
    createdAt: '2026-01-08T00:00:00Z',
  },
  {
    id: 'loc-dk-bent-row',
    campaignId: 'campaign-drakkenheim',
    name: 'Bent Row',
    aliases: ['Прогнутый ряд'],
    type: 'district',
    parentLocationId: 'loc-dk-city',
    description:
      "Подземный район Дракенхейма в Районе Спицы за Крысиным гнездом. Логово нескольких группировок Queen's Men: Собаки, Катакомбные Кобры, Роза и Шипы, Карта-Бубен и Штыри, Раненые Сердца.",
    createdAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'loc-dk-rat-nest',
    campaignId: 'campaign-drakkenheim',
    name: 'Rat Nest',
    aliases: ['Крысиное гнездо'],
    type: 'dungeon',
    parentLocationId: 'loc-dk-city',
    description: 'Гнездо крыс в руинах Дракенхейма. Здесь была заперта Петра Лэнг. Зачищено партией.',
    createdAt: '2025-10-01T00:00:00Z',
  },

  // ── Drakkenheim — Bent Row sub-locations ────────────────────────────────
  {
    id: 'loc-dk-old-imperial-pub',
    campaignId: 'campaign-drakkenheim',
    name: 'Old Imperial Pub',
    aliases: ['Старый Имперский Паб'],
    type: 'building',
    subtype: 'tavern',
    parentLocationId: 'loc-dk-bent-row',
    description:
      "Подземная таверна в Прогнутом ряду. База группы «Роза и Шипы» Людей Королевы. Владеет Роза Карвер, бармен — Израэль.",
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'loc-dk-sweaty-bugbear',
    campaignId: 'campaign-drakkenheim',
    name: 'Sweaty Bugbear',
    aliases: ['Трактир Потный Багбир'],
    type: 'building',
    subtype: 'tavern',
    parentLocationId: 'loc-dk-bent-row',
    description:
      "Подземная таверна в Прогнутом ряду. Место Вероники Яд. Здесь партии дали бесплатный стейк как извинение. Патрикеевна попала дротиком в гнома, привязанного к мишени.",
    createdAt: '2026-03-16T00:00:00Z',
  },
  {
    id: 'loc-dk-smis-palace',
    campaignId: 'campaign-drakkenheim',
    name: "Smi's Palace",
    aliases: ['Дворец Сми'],
    type: 'building',
    subtype: 'tavern',
    parentLocationId: 'loc-dk-bent-row',
    description:
      "Подземное заведение в Прогнутом ряду. База группы «Раненые Сердца» Людей Королевы. Хозяин — Кристиан Лам, официантка-эльфийка Тильда. Партия ночевала здесь после сессии 15.",
    createdAt: '2026-02-26T00:00:00Z',
  },
  {
    id: 'loc-dk-arena',
    campaignId: 'campaign-drakkenheim',
    name: 'Arena',
    aliases: ['Подземная Арена'],
    type: 'dungeon',
    subtype: 'arena',
    parentLocationId: 'loc-dk-bent-row',
    description:
      'Большая подземная арена в канализации под Прогнутым рядом. Пол в крови и грязи, скамейки для ~40 зрителей, боевое кольцо с деревянными баррикадами, VIP-площадка. Организатор — Булл (обезображенное лицо, один слепой глаз). Ставки принимает полурослик Рокки.',
    createdAt: '2026-03-09T00:00:00Z',
  },
];
