import type { NPC } from '@/entities/npc';

export const MOCK_NPCS: NPC[] = [

  // ════════════════════════════════════════════════════════════
  //  FARCHESTER CAMPAIGN
  // ════════════════════════════════════════════════════════════

  {
    id: 'npc-kronheyv',
    campaignId: 'campaign-farchester',
    name: 'Лорд-Адмирал Эдвард Кронхейав',
    aliases: ['Маркграф', 'Lord-Admiral', 'Edward Kronhev'],
    status: 'alive',
    gender: 'male',
    age: 57,
    species: 'Human',
    speciesId: 'species-human',
    appearance: 'Усталый, осунувшийся. Морские трофеи в резиденции. Жена и стража прячут от него алкоголь.',
    personality: 'Авторитарен, холоден, прячет усталость за высокомерием. Презирает тех, кто ставит под сомнение его власть. В разговоре — краток и требователен. Редкие моменты искренности выдают человека, раздавленного должностью.',
    description:
      'Маркграф Степной Марки. Объявил сухой закон и комендантский час. Открыто презирает эльфов и степные народы. Утверждает, что партия — первые приезжие с момента его назначения. Просил найти особый алкоголь у Йорверта.',
    gmNotes: 'Возможно является причиной пересыхания реки через Тутса. Знает больше, чем говорит.',
    locations: ['Резиденция Кронхейава', 'Фарчестер'],
    groupMemberships: [
      { npcId: 'npc-kronheyv', groupId: 'faction-fc-red', relation: 'Leader' },
    ],
    createdAt: '2026-02-24T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  {
    id: 'npc-stoungriv',
    campaignId: 'campaign-farchester',
    name: 'Торбальд Стоунгрив',
    aliases: ['Бургомистр', 'Burgmaster Stoungriv'],
    status: 'alive',
    gender: 'male',
    age: 46,
    species: 'Human',
    speciesId: 'species-human',
    appearance:
      'Худощавый мужчина средних лет с короткими тёмными волосами и суровым взглядом. Разноцветный наряд с ромбическим узором, красный берет. Всегда при свитках.',
    personality: 'Расчётлив и двуличен — улыбается в глаза, пока манипулирует за спиной. Искренне любит город, но любовь эта оправдывает любые средства. Никогда не проявляет страха открыто. Любит, когда его недооценивают.',
    description:
      'Бургомистр Фарчестера. Изначально из свободолюбивых. Нанял партию за 50 gp за каждое имя агента Ордена Гефары. Выдал документы — обязывают горожан помогать предъявителю. Казна в недостаче на 5000 золотых.',
    gmNotes:
      'КЛЮЧЕВОЙ ВОПРОС: партия И ЕСТЬ агенты Гефары. Вариант А — не знает. Вариант Б — знает, но держит под контролем. Фраза «все боятся бургомистра» (Тутс) — намёк.',
    locations: ['Ратуша', 'Фарчестер'],
    groupMemberships: [
      { npcId: 'npc-stoungriv', groupId: 'faction-fc-blue', relation: 'Leader' },
    ],
    createdAt: '2026-02-24T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  {
    id: 'npc-edit-hargrave',
    campaignId: 'campaign-farchester',
    name: 'Эдит Харгрейв',
    aliases: ['Hargrave'],
    status: 'alive',
    gender: 'female',
    age: 31,
    species: 'Human',
    speciesId: 'species-human',
    appearance: 'Смуглая кожа, тёмные волосы. Чёрно-красный табард поверх кольчуги, красный плащ, меч у пояса.',
    description: 'Связная и представитель Кронхейава. Приглашала партию к Лорд-Адмиралу.',
    locations: ['Резиденция Кронхейава'],
    groupMemberships: [
      { npcId: 'npc-edit-hargrave', groupId: 'faction-fc-red', relation: 'Member' },
    ],
    createdAt: '2026-02-24T00:00:00Z',
    updatedAt: '2026-02-24T00:00:00Z',
  },

  {
    id: 'npc-eshborn',
    campaignId: 'campaign-farchester',
    name: 'Гарет Риддерх Эшборн',
    aliases: ['Gareth Eshborn'],
    status: 'alive',
    gender: 'male',
    age: 44,
    species: 'Human',
    speciesId: 'species-human',
    appearance:
      'Мужчина средних лет, седоватые волосы, уверенный взгляд. Синий жилет со звёздчатым узором, кольчуга, изогнутый меч.',
    description: 'Местный житель. Привёл партию к ратуше. Поставил 5gp на смерть полурослика.',
    locations: ['Фарчестер'],
    groupMemberships: [],
    createdAt: '2026-02-24T00:00:00Z',
    updatedAt: '2026-02-24T00:00:00Z',
  },

  {
    id: 'npc-yorvert',
    campaignId: 'campaign-farchester',
    name: 'Йорверт',
    aliases: ['Iorwerth', 'Тавернщик'],
    status: 'alive',
    gender: 'male',
    age: 45,
    species: 'Human',
    speciesId: 'species-human',
    appearance:
      'Мужчина лет сорока пяти, светло-каштановые волосы до плеч, аккуратная седеющая борода. Добродушная улыбка. Зелёный жилет, белая рубашка, кельтская застёжка. Всегда с кружкой.',
    personality: 'Тёплый и незлобивый. Медленно составляет мнение о людях — зато надолго. Избегает конфликтов, но не трус. Немного старомоден: верит, что хорошее пиво решает больше проблем, чем политика.',
    description:
      'Тавернщик таверны «Ы Куру Айр». Центрист. Недолюбливает эльфов. Признался, что сейчас не варит алкоголь — нет оборудования. Помог партии сварить 2 бутылки особого алкоголя.',
    locations: ['Таверна Ы Куру Айр'],
    groupMemberships: [],
    relations: [{ npcId: 'npc-mirian', type: 'child', note: 'Мириан верч Йорверт — дочь' }],
    createdAt: '2026-02-24T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  {
    id: 'npc-tuts',
    campaignId: 'campaign-farchester',
    name: 'Тутс',
    aliases: ['Tuts', 'Маг башни'],
    status: 'alive',
    gender: 'male',
    age: 118,
    species: 'Gnome',
    speciesId: 'species-gnome',
    appearance: 'Гном-маг. Раздражён учеником, который полгода не может освоить Mage Hand.',
    personality: 'Блестящий ум в вечно нетерпеливой оболочке. Говорит быстро и ожидает, что собеседник поспевает. Ненавидит некомпетентность, но тайно ценит упорство. Скрывает, что ему одиноко.',
    description:
      'Маг, хозяин башни в Фарчестере. Башня охраняется каменным терьером-стражем с загадками. Первый этаж для очень крупных существ, второй — огромное количество часов. Имеет какую-то связь с Стоунгривом.',
    gmNotes: 'Возможно тот самый гном, который «сделал магию с рекой» у гоблинов и заключил договор с Гнурком.',
    locations: ['Башня мага'],
    groupMemberships: [],
    createdAt: '2026-03-02T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  {
    id: 'npc-gvilim',
    campaignId: 'campaign-farchester',
    name: 'Гвилим ап Оуайн',
    aliases: ['Gwilym ap Owain'],
    status: 'alive',
    gender: 'male',
    age: 20,
    species: 'Human',
    speciesId: 'species-human',
    appearance:
      'Невысокий молодой парень с буйными рыжими вьющимися волосами и широкой искренней улыбкой. Светло-карие глаза. Льняная рубашка, коричневый жилет. Рассеянный.',
    description:
      'Ученик мага Тутса в башне. Уже полгода не может нормально освоить Mage Hand — Тутс бесится. Тот самый паренёк из первой сессии, которому Эсме помогала в таверне.',
    locations: ['Башня мага'],
    groupMemberships: [],
    createdAt: '2026-02-20T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  {
    id: 'npc-vaysiriel',
    campaignId: 'campaign-farchester',
    name: 'Вайсириэль',
    aliases: ['Waysiryel'],
    status: 'unknown',
    gender: 'female',
    age: 245,
    species: 'Elf',
    speciesId: 'species-elf',
    appearance:
      'Эльфийка с длинными серебристо-белыми волосами с серым отливом. Красные/розовые глаза с тёмными веками. Острые уши, серьга-кинжал. Тёмно-зелёная броня. Загадочная полуулыбка — выглядит опасной.',
    description: 'Упомянута в сессии 4. Подробности неизвестны. Кажется опасной.',
    locations: ['Фарчестер'],
    groupMemberships: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  {
    id: 'npc-elarven',
    campaignId: 'campaign-farchester',
    name: 'Эларвен',
    aliases: ['Elarwen'],
    status: 'alive',
    gender: 'male',
    age: 183,
    species: 'Elf',
    speciesId: 'species-elf',
    description:
      'Предводитель эльфийского лагеря за воротами Фарчестера. Город загрязняет лес — эльфы готовы к сотрудничеству в обмен на решение проблемы.',
    locations: ['За воротами Фарчестера'],
    groupMemberships: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },

  {
    id: 'npc-gnurk',
    campaignId: 'campaign-farchester',
    name: 'Гнурк',
    aliases: ['Gnurk'],
    status: 'alive',
    gender: 'male',
    age: 35,
    species: 'Goblin',
    speciesId: 'species-goblin',
    description:
      'Шаман и лидер гоблинского лагеря за воротами. Пещеры гоблинов затапливает. Заключил договор с гномом, который «сделал магию с рекой» (возможно Тутс). После — у гоблинов начали расти грибы. В сессии 5 попросил принести особую плесень из города.',
    gmNotes: 'Договор с Тутсом — ключевая зацепка. Что именно договорились?',
    locations: ['За воротами Фарчестера'],
    groupMemberships: [],
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-18T00:00:00Z',
  },

  {
    id: 'npc-mirian',
    campaignId: 'campaign-farchester',
    name: 'Мириан верч Йорверт',
    aliases: ['Miriam', 'Мириа'],
    status: 'unknown',
    gender: 'female',
    age: 19,
    species: 'Human',
    speciesId: 'species-human',
    appearance: 'Молодая женщина с тёмно-каштановыми вьющимися волосами, зелёные ленты. Веснушки, зелёные глаза. Зелёный корсет, белый фартук.',
    description: 'Возможно родственница тавернщика Йорверта. Пока не встречена лично.',
    locations: ['Таверна Ы Куру Айр'],
    groupMemberships: [],
    relations: [{ npcId: 'npc-yorvert', type: 'parent', note: 'Verch — daughter of Iorwerth' }],
    createdAt: '2026-02-24T00:00:00Z',
    updatedAt: '2026-02-24T00:00:00Z',
  },

  {
    id: 'npc-kragven',
    campaignId: 'campaign-farchester',
    name: 'Крагвен Раудвегр',
    aliases: ['Kragwen Raudvegr'],
    status: 'alive',
    gender: 'male',
    age: 82,
    species: 'Dwarf',
    speciesId: 'species-dwarf',
    description: 'Глава каравана дварфов. Самый важный из дварфов группы. Один из них владел картой местности. Возможно умеют варить алкоголь.',
    locations: ['Фарчестер'],
    groupMemberships: [],
    createdAt: '2026-03-02T00:00:00Z',
    updatedAt: '2026-03-02T00:00:00Z',
  },


  // ════════════════════════════════════════════════════════════
  //  DRAKKENHEIM CAMPAIGN
  // ════════════════════════════════════════════════════════════

  // ── The Hooded Lanterns ─────────────────────────────────────

  {
    id: 'npc-drexel',
    campaignId: 'campaign-drakkenheim',
    name: 'Elias Drexel',
    aliases: ['Элиас Дресель'],
    status: 'alive',
    gender: 'male',
    age: 47,
    species: 'Human',
    speciesId: 'species-human',
    personality: 'Военный до мозга костей: дисциплинирован, лаконичен, миссия прежде всего. Не говорит лишнего — каждое слово взвешено. Уважает тех, кто держит слово. Усталость от войны скрывает за строгим лицом.',
    description: 'Командор Фонарей (The Hooded Lanterns). Союзник партии.',
    locations: ['Emberwood Village'],
    groupMemberships: [
      { npcId: 'npc-drexel', groupId: 'faction-dk-lanterns', relation: 'Leader' },
    ],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },

  {
    id: 'npc-ansom-lang',
    campaignId: 'campaign-drakkenheim',
    name: 'Ansom Lang',
    aliases: ['Ансом Лэнг'],
    status: 'alive',
    gender: 'male',
    age: 28,
    species: 'Human',
    speciesId: 'species-human',
    description:
      'Член Фонарей. Хочет восстановить старый город, столицу и нацию. Брат Петры Лэнг. В сессии 5 попросил спасти сестру — выполнено в сессии 7.',
    locations: ['Emberwood Watchtower'],
    groupMemberships: [
      { npcId: 'npc-ansom-lang', groupId: 'faction-dk-lanterns', relation: 'Member' },
    ],
    relations: [{ npcId: 'npc-petra-lang', type: 'sibling' }],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },

  {
    id: 'npc-petra-lang',
    campaignId: 'campaign-drakkenheim',
    name: 'Petra Lang',
    aliases: ['Петра Лэнг'],
    status: 'alive',
    gender: 'female',
    age: 26,
    species: 'Human',
    speciesId: 'species-human',
    description:
      'Сестра Ансома Лэнга. Пропала в патруле, захвачена крысами. Спасена партией из Крысиного гнезда (сессия 7). Рассказала, что Аметисты скрывают секрет про Оскара Йорена.',
    locations: ['Emberwood Watchtower'],
    groupMemberships: [
      { npcId: 'npc-petra-lang', groupId: 'faction-dk-lanterns', relation: 'Member' },
    ],
    relations: [{ npcId: 'npc-ansom-lang', type: 'sibling' }],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2026-01-15T00:00:00Z',
  },

  {
    id: 'npc-raine',
    campaignId: 'campaign-drakkenheim',
    name: 'Raine Highlash',
    aliases: ['Рейн Харлаш'],
    status: 'alive',
    gender: 'female',
    age: 34,
    species: 'Human',
    speciesId: 'species-human',
    description: 'Капитан дозора Фонарей в Часовой башне Эмбервуда. Первая встреча в сессии 1.',
    locations: ['Emberwood Watchtower'],
    groupMemberships: [
      { npcId: 'npc-raine', groupId: 'faction-dk-lanterns', relation: 'Member' },
    ],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-09-01T00:00:00Z',
  },

  // ── Queen's Men ─────────────────────────────────────────────

  {
    id: 'npc-rosa-carver',
    campaignId: 'campaign-drakkenheim',
    name: 'Rosa Carver',
    aliases: ['Роза Карвер'],
    status: 'hostile',
    gender: 'female',
    age: 36,
    species: 'Human',
    speciesId: 'species-human',
    appearance: 'Рыжеволосая женщина-воин в тёмной броне.',
    personality: 'Деловая и беспощадная — без лишних слов. Улыбается ровно столько, сколько нужно для сделки. Уважает силу и ненавидит сантименты. Никогда не угрожает дважды.',
    description: 'Босс «Розы и Шипов» — подгруппы Людей Королевы. База в Старом Имперском Пабе и Прогнутом ряду.',
    locations: ['Old Imperial Pub', 'Bent Row'],
    groupMemberships: [
      { npcId: 'npc-rosa-carver', groupId: 'faction-dk-queens', relation: 'Leader', subfaction: 'Rose and Thorns' },
    ],
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2025-12-15T00:00:00Z',
  },

  {
    id: 'npc-kristian-lam',
    campaignId: 'campaign-drakkenheim',
    name: 'Kristian Lam',
    aliases: ['Кристиан Лам'],
    status: 'alive',
    gender: 'male',
    age: 42,
    species: 'Human',
    speciesId: 'species-human',
    description: 'Босс «Раненых сердец» — подгруппы Людей Королевы. База в Дворце Сми и Прогнутом ряду. Полная фамилия неизвестна.',
    locations: ["Smi's Palace", 'Bent Row'],
    groupMemberships: [
      { npcId: 'npc-kristian-lam', groupId: 'faction-dk-queens', relation: 'Leader', subfaction: 'Wounded Hearts' },
    ],
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2025-10-01T00:00:00Z',
  },

  {
    id: 'npc-veronika-yad',
    campaignId: 'campaign-drakkenheim',
    name: 'Veronika Yad',
    aliases: ['Вероника Яд', 'Veronica Poison'],
    status: 'alive',
    gender: 'female',
    age: 31,
    species: 'Human',
    speciesId: 'species-human',
    appearance: 'Мрачная женщина с тёмными волосами.',
    description:
      'Босс «Канализационных кобр» — подгруппы Людей Королевы. База в Прогнутом ряду. Встречена в сессии 17 в Потном Багбире.',
    locations: ['Bent Row', 'Sweaty Bugbear'],
    groupMemberships: [
      { npcId: 'npc-veronika-yad', groupId: 'faction-dk-queens', relation: 'Leader', subfaction: 'Sewer Cobras' },
    ],
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2026-03-16T00:00:00Z',
  },

  {
    id: 'npc-serpenta',
    campaignId: 'campaign-drakkenheim',
    name: 'Serpenta',
    aliases: ['Серпента'],
    status: 'alive',
    gender: 'female',
    age: 23,
    species: 'Human',
    speciesId: 'species-human',
    appearance: 'Молодая женщина в чёрном плаще с капюшоном.',
    description: 'Канализационные кобры. Знакомая Вермиры.',
    locations: ['Bent Row'],
    groupMemberships: [
      { npcId: 'npc-serpenta', groupId: 'faction-dk-queens', relation: 'Member', subfaction: 'Sewer Cobras' },
    ],
    createdAt: '2025-11-01T00:00:00Z',
    updatedAt: '2025-11-01T00:00:00Z',
  },

  {
    id: 'npc-bufotenia',
    campaignId: 'campaign-drakkenheim',
    name: 'Bufotenia',
    aliases: ['Буфотения'],
    status: 'alive',
    gender: 'female',
    species: 'Unknown',
    description:
      'Канализационные кобры. В сессии 11 в Прогнутом ряду — глаза загораются красным, видит невидимое.',
    locations: ['Bent Row'],
    groupMemberships: [
      { npcId: 'npc-bufotenia', groupId: 'faction-dk-queens', relation: 'Member', subfaction: 'Sewer Cobras' },
    ],
    createdAt: '2025-11-01T00:00:00Z',
    updatedAt: '2025-11-01T00:00:00Z',
  },

  {
    id: 'npc-muskarina',
    campaignId: 'campaign-drakkenheim',
    name: 'Muskarina',
    aliases: ['Мускарина'],
    status: 'alive',
    gender: 'female',
    species: 'Unknown',
    description: 'Канализационные кобры. Детали неизвестны.',
    locations: ['Bent Row'],
    groupMemberships: [
      { npcId: 'npc-muskarina', groupId: 'faction-dk-queens', relation: 'Member', subfaction: 'Sewer Cobras' },
    ],
    createdAt: '2025-11-01T00:00:00Z',
    updatedAt: '2025-11-01T00:00:00Z',
  },

  {
    id: 'npc-izrael',
    campaignId: 'campaign-drakkenheim',
    name: 'Izrael',
    aliases: ['Израель', 'Israel'],
    status: 'alive',
    gender: 'male',
    age: 37,
    species: 'Human',
    speciesId: 'species-human',
    description: 'Бармен в Старом Имперском Пабе. Роза и Шипы.',
    locations: ['Old Imperial Pub', 'Bent Row'],
    groupMemberships: [
      { npcId: 'npc-izrael', groupId: 'faction-dk-queens', relation: 'Member', subfaction: 'Rose and Thorns' },
    ],
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2025-10-01T00:00:00Z',
  },

  {
    id: 'npc-tilda',
    campaignId: 'campaign-drakkenheim',
    name: 'Tilda',
    aliases: ['Тильда'],
    status: 'alive',
    gender: 'female',
    age: 178,
    species: 'Elf',
    speciesId: 'species-elf',
    description: 'Эльфийка-официантка в Дворце Сми. Раненые сердца.',
    locations: ["Smi's Palace", 'Bent Row'],
    groupMemberships: [
      { npcId: 'npc-tilda', groupId: 'faction-dk-queens', relation: 'Member', subfaction: 'Wounded Hearts' },
    ],
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2025-10-01T00:00:00Z',
  },

  {
    id: 'npc-bloodhound',
    campaignId: 'campaign-drakkenheim',
    name: 'Bloodhound',
    aliases: ['Бладхаунд'],
    status: 'alive',
    gender: 'male',
    age: 26,
    species: 'Tiefling',
    speciesId: 'species-tiefling',
    appearance: 'Рогатый, темноватый персонаж.',
    description: 'Боец на арене в Прогнутом ряду. Базируется в Потном Багбире. Группа неизвестна.',
    locations: ['Sweaty Bugbear', 'Bent Row', 'Arena'],
    groupMemberships: [
      { npcId: 'npc-bloodhound', groupId: 'faction-dk-queens', relation: 'Member' },
    ],
    createdAt: '2025-11-01T00:00:00Z',
    updatedAt: '2025-11-01T00:00:00Z',
  },

  {
    id: 'npc-dorian',
    campaignId: 'campaign-drakkenheim',
    name: 'Dorian Derzky',
    aliases: ['Дориан Дерзкий', 'Dorian the Bold'],
    status: 'alive',
    gender: 'male',
    age: 64,
    species: 'Human',
    speciesId: 'species-human',
    appearance: 'Пожилой мужчина с седой бородой, видавший виды.',
    description: 'Боец на арене в Прогнутом ряду. Раненые сердца.',
    locations: ["Smi's Palace", 'Bent Row', 'Arena'],
    groupMemberships: [
      { npcId: 'npc-dorian', groupId: 'faction-dk-queens', relation: 'Member', subfaction: 'Wounded Hearts' },
    ],
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2025-10-01T00:00:00Z',
  },

  {
    id: 'npc-tony',
    campaignId: 'campaign-drakkenheim',
    name: 'Tony',
    aliases: ['Тони'],
    status: 'alive',
    gender: 'male',
    age: 36,
    species: 'Human',
    speciesId: 'species-human',
    appearance: 'Массивный, грузный, страшноватый на вид.',
    description: '«Вечно спящий охранник Тига» — охраняет кого-то по имени Тига. Прогнутый ряд. Группа неизвестна.',
    locations: ['Bent Row'],
    groupMemberships: [
      { npcId: 'npc-tony', groupId: 'faction-dk-queens', relation: 'Member' },
    ],
    createdAt: '2025-11-01T00:00:00Z',
    updatedAt: '2025-11-01T00:00:00Z',
  },

  // ── The Amethyst Academy ────────────────────────────────────

  {
    id: 'npc-eldric',
    campaignId: 'campaign-drakkenheim',
    name: 'Eldric Runeweaver',
    aliases: ['Элдрик Руноткач'],
    status: 'alive',
    gender: 'male',
    age: 53,
    species: 'Human',
    speciesId: 'species-human',
    description:
      'Руководит местным конклавом Аметистовой Академии. В башне во время падения метеорита находился главный маг с посохом (тем самым). Скрывает информацию об Оскаре Йорене.',
    gmNotes: 'Ключевая фигура тайны с Оскаром. Что он знает?',
    locations: ['Drakkenheim'],
    groupMemberships: [
      { npcId: 'npc-eldric', groupId: 'faction-dk-amethyst', relation: 'Leader' },
    ],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-09-01T00:00:00Z',
  },

  {
    id: 'npc-river',
    campaignId: 'campaign-drakkenheim',
    name: 'River',
    aliases: ['Река'],
    status: 'alive',
    gender: 'female',
    age: 28,
    species: 'Tiefling',
    speciesId: 'species-tiefling',
    personality: 'Острая, закрытая, снисходительна к тем, кто ей нравится — и это почти комплимент. Говорит с ленцой, но слушает внимательно. Держит дистанцию и раздражается, когда её нарушают.',
    description:
      'Тифлинг-варлок. Управляет отделением Аметистов в Эмбервуде. По ночам зависает в отдельной библиотеке Красного Льва. Прагматична как чёрт. Странно реагирует на имя Оскар Йорен. Поделилась точкой про Мельницу Эккермена. Отправляла телепатические сообщения.',
    gmNotes: 'Почему неприязнь к Йорену? Она что-то знает или сама замешана?',
    locations: ['Red Lion Hotel', 'Emberwood Village'],
    groupMemberships: [
      { npcId: 'npc-river', groupId: 'faction-dk-amethyst', relation: 'Member' },
    ],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2026-03-01T00:00:00Z',
  },

  {
    id: 'npc-sebastian',
    campaignId: 'campaign-drakkenheim',
    name: 'Sebastian',
    aliases: ['Себастьян'],
    status: 'alive',
    gender: 'male',
    age: 24,
    species: 'Human',
    speciesId: 'species-human',
    description:
      'Ученик Оскара Йорена. Ушёл из Аметистовой Академии. Украл тома по вызову, некромантии и, возможно, трансмутации. Его перестали финансировать. Группа: Марко, Джемма, Таррин, Болтер, Копперпот.',
    gmNotes: 'Связан ли с заражёнными зельями? Куда ушёл после Академии?',
    locations: ['Drakkenheim'],
    groupMemberships: [],
    relations: [{ npcId: 'npc-oscar-yoren', type: 'mentor' }],
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2025-12-01T00:00:00Z',
  },

  // ── Unknown / Mystery ───────────────────────────────────────

  {
    id: 'npc-oscar-yoren',
    campaignId: 'campaign-drakkenheim',
    name: 'Oscar Yoren',
    aliases: ['Оскар Йорен', 'Оскар'],
    status: 'unknown',
    gender: 'male',
    age: 52,
    species: 'Human',
    speciesId: 'species-human',
    personality: 'Параноик-гений. Работает в изоляции по собственному выбору. Никому не доверяет достаточно долго. Способен быть обаятельным, когда ему что-то нужно. Его исчезновение — не случайность.',
    description:
      'Бывший? член Аметистовой Академии. Река знает где он — но молчит. Элдрик Руноткач скрывает информацию. Себастьян — его ученик. Иоганн Призроткач имел с ним дела. Связан с заражёнными зельями чистоты (квест Фонарей).',
    gmNotes: 'ЦЕНТРАЛЬНАЯ ТАЙНА КАМПАНИИ. Что скрывают Аметисты? Жив ли он вообще?',
    locations: ['Unknown'],
    groupMemberships: [
      { npcId: 'npc-oscar-yoren', groupId: 'faction-dk-amethyst', relation: 'Member' },
    ],
    relations: [{ npcId: 'npc-sebastian', type: 'pupil' }],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },

  {
    id: 'npc-ghostweaver',
    campaignId: 'campaign-drakkenheim',
    name: 'Johann Ghostweaver',
    aliases: ['Иоганн Призроткач'],
    status: 'unknown',
    gender: 'male',
    age: 63,
    species: 'Human',
    speciesId: 'species-human',
    description:
      'Научил Зою лечению от делириума. Имел дела с Оскаром Йореном. Партия его ещё не встречала — нужно найти.',
    gmNotes: 'Ключ к пониманию связи Зоя → Йорен. Где он сейчас?',
    locations: ['Unknown'],
    groupMemberships: [],
    relations: [
      { npcId: 'npc-zoya', type: 'pupil', note: 'Научил лечению от делириума' },
      { npcId: 'npc-oscar-yoren', type: 'acquaintance', note: 'Имел дела' },
    ],
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },

  // ── Followers of the Falling Fire ───────────────────────────

  {
    id: 'npc-katya-brown',
    campaignId: 'campaign-drakkenheim',
    name: 'Katya Brown',
    aliases: ['Катя Браун', 'Tanya Brown'],
    status: 'alive',
    gender: 'female',
    age: 37,
    species: 'Human',
    speciesId: 'species-human',
    description:
      'Сокурсница Вермиры. Раньше была в Священном Пламени, но переметнулась к культистам после Резни Магов 15 лет назад. Культистка у Врат Чемпионов. В сессии 13 — отобрала с фанатиками Bag of Holding.',
    locations: ["Champion's Gate"],
    groupMemberships: [
      { npcId: 'npc-katya-brown', groupId: 'faction-dk-flame', relation: 'Member' },
    ],
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },

  {
    id: 'npc-lucretia',
    campaignId: 'campaign-drakkenheim',
    name: 'Lucretia Mathias',
    aliases: ['Лукреция Матиас'],
    status: 'alive',
    gender: 'female',
    age: 44,
    species: 'Human',
    speciesId: 'species-human',
    description: 'Возможно управляет культистами Падшего Пламени у Врат Чемпионов. Встречена в сессии 10.',
    locations: ["Champion's Gate"],
    groupMemberships: [
      { npcId: 'npc-lucretia', groupId: 'faction-dk-flame', relation: 'Leader' },
    ],
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2025-10-01T00:00:00Z',
  },

  // ── Knights of the Silver Order ─────────────────────────────

  {
    id: 'npc-bryce-landry',
    campaignId: 'campaign-drakkenheim',
    name: 'Sir Bryce Landry',
    aliases: ['Брайс Лендри', 'Bryce Landry'],
    status: 'alive',
    gender: 'male',
    age: 39,
    species: 'Human',
    speciesId: 'species-human',
    description:
      'Рыцарь Серебряного Ордена. Захарис его искал — нашли. Корвин попал ему Magic Missile в оба коленных чашечки (сессия 14).',
    locations: ['Drakkenheim'],
    groupMemberships: [
      { npcId: 'npc-bryce-landry', groupId: 'faction-dk-silver', relation: 'Member' },
    ],
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },

  // ── Independent NPCs ────────────────────────────────────────

  {
    id: 'npc-tobias-crowe',
    campaignId: 'campaign-drakkenheim',
    name: 'Tobias Crowe',
    aliases: ['Тобиас Кроу'],
    status: 'alive',
    gender: 'male',
    age: 44,
    species: 'Human',
    speciesId: 'species-human',
    description: 'Владеет кузней Crowe and Sons в Эмбервуде. Вероятно отец Эммы Кроу. Дорого, но делают на заказ.',
    locations: ['Crowe and Sons Smithy', 'Emberwood Village'],
    groupMemberships: [],
    relations: [{ npcId: 'npc-emma-crowe', type: 'child' }],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-09-01T00:00:00Z',
  },

  {
    id: 'npc-emma-crowe',
    campaignId: 'campaign-drakkenheim',
    name: 'Emma Crowe',
    aliases: ['Эмма Кроу'],
    status: 'alive',
    gender: 'female',
    age: 11,
    species: 'Human',
    speciesId: 'species-human',
    appearance: 'Рыжеволосая маленькая девочка. Супер энергичная.',
    description: 'Дочка кузнеца Тобиаса. За 1 gp проводит экскурсии по Эмбервуду. Знает слухи.',
    locations: ['Crowe and Sons Smithy', 'Emberwood Village'],
    groupMemberships: [],
    relations: [{ npcId: 'npc-tobias-crowe', type: 'parent' }],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-09-01T00:00:00Z',
  },

  {
    id: 'npc-karin-alsberg',
    campaignId: 'campaign-drakkenheim',
    name: 'Karin Alsberg',
    aliases: ['Карин Альцберг'],
    status: 'alive',
    gender: 'female',
    age: 42,
    species: 'Human',
    speciesId: 'species-human',
    personality: 'Практична и гостеприимна — без лишней теплоты. Всегда занята, редко сидит. Быстро распознаёт проблемы и решает их до того, как те выросли. Защищает гостей, но не терпит дебоширов.',
    description: 'Владелица Bark and Buzzard (Коршун и Ищейка). Есть муж Holger.',
    locations: ['Bark and Buzzard', 'Emberwood Village'],
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-09-01T00:00:00Z',
  },

  {
    id: 'npc-zoya',
    campaignId: 'campaign-drakkenheim',
    name: 'Zoya',
    aliases: ['Зоя'],
    status: 'missing',
    gender: 'female',
    age: 72,
    species: 'Human',
    speciesId: 'species-human',
    personality: 'Говорит полуправдами и намёками — не из вредности, а потому что так видит мир. Тихая, но с характером. Её молчание значит больше, чем слова других. Любит Патрикеевну как родную.',
    description:
      'Старушка-отшельница, поклоняется Старым богам. Не любима в Эмбервуде. Продаёт янтарные шарики. Подруга Патрикеевны. Знает лечение от делириума (научил Иоганн Призроткач). В сессии 17 оказалась допельгангером Крадущего Мысли — настоящая Зоя неизвестно где.',
    gmNotes: 'Где настоящая Зоя? Зачем Крадущий Мысли за ней? Связь с Йореном через Призроткача.',
    locations: ['Zoya House'],
    groupMemberships: [],
    relations: [{ npcId: 'npc-ghostweaver', type: 'mentor', note: 'Научил лечению от делириума' }],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2026-03-16T00:00:00Z',
  },

  {
    id: 'npc-aldor',
    campaignId: 'campaign-drakkenheim',
    name: 'Aldor',
    aliases: ['Алдор', 'Алдор Великан', 'Джинн'],
    status: 'alive',
    gender: 'male',
    age: 1200,
    species: 'Djinn',
    personality: 'Абсолютно транзакционен — ни тепла, ни злобы. Относится к смертным как к контрагентам. Терпелив ровно настолько, насколько выгодно. Сделки — его язык, угрозы — его пунктуация.',
    description:
      'Джинн. Продаёт магические предметы на ночном рынке. Долг Корвина 500 gp за уничтоженный Bag of Holding — погашен в сессии 17 проклятым огненным мечом. Находится в астрале, нашёл скипетр — предложил обмен. По словам Людей Королевы — заточён в этом месте.',
    gmNotes: 'Скипетр в астрале — что это? Выгодна ли сделка?',
    locations: ['Marketplace'],
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2026-03-16T00:00:00Z',
  },

  {
    id: 'npc-orson',
    campaignId: 'campaign-drakkenheim',
    name: 'Orson Fairweather',
    aliases: ['Орсон Фейрузер'],
    status: 'alive',
    gender: 'male',
    age: 40,
    species: 'Human',
    speciesId: 'species-human',
    description:
      'Торговец делириумом на ночном рынке. Маленький контейнер 4 gp, средний 10 gp, большой 20 gp. Партия продала ему делириум за 27 gp (сессия 5).',
    locations: ['Marketplace', 'Emberwood Village'],
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-10-01T00:00:00Z',
  },

  {
    id: 'npc-armin',
    campaignId: 'campaign-drakkenheim',
    name: 'Armin Gainsbury',
    aliases: ['Армин Гейнсбери'],
    status: 'alive',
    gender: 'male',
    age: 38,
    species: 'Human',
    speciesId: 'species-human',
    description: 'Торгует экипировкой для приключений на рынке Эмбервуда.',
    locations: ['Marketplace', 'Emberwood Village'],
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-09-01T00:00:00Z',
  },

  {
    id: 'npc-eren-marlow',
    campaignId: 'campaign-drakkenheim',
    name: 'Eren Marlow',
    aliases: ['Эрен Марлоу'],
    status: 'alive',
    gender: 'male',
    age: 33,
    species: 'Human',
    speciesId: 'species-human',
    description:
      'Довёз партию до Эмбервуда в сессии 1. Продаёт базовые припасы на рынке. Работает ночью. Может познакомить с Армином Гейнсбери.',
    locations: ['Marketplace', 'Emberwood Village'],
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-09-01T00:00:00Z',
  },

  {
    id: 'npc-madam-rochelle',
    campaignId: 'campaign-drakkenheim',
    name: 'Madam Rochelle',
    aliases: ['Мадам Рошель'],
    status: 'alive',
    gender: 'female',
    age: 52,
    species: 'Human',
    speciesId: 'species-human',
    personality: 'Рафинированная и наблюдательная. Видит всё, говорит — ничего лишнего. Держит нейтралитет как защитный щит. Умеет создать ощущение, что вы её единственный важный гость.',
    description: 'Управляет Gilded Lily (Позолоченная Лилия). Вечера открытых выступлений.',
    locations: ['Gilded Lily', 'Emberwood Village'],
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-09-01T00:00:00Z',
  },

  {
    id: 'npc-antoine-megara',
    campaignId: 'campaign-drakkenheim',
    name: 'Antoine Megara',
    aliases: ['Антуан Мегара'],
    status: 'alive',
    gender: 'male',
    age: 46,
    species: 'Human',
    speciesId: 'species-human',
    description:
      'Богатый дворянин. Последователь Священного Пламени (не в составе фракции). Прибыл в Дракенхейм по заданию. Партия забрала у него 30 gp (сессия 12). Команда «Прекраснейший Дом Мегара».',
    locations: ['Drakkenheim'],
    groupMemberships: [],
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },

  {
    id: 'npc-endra-jansen',
    campaignId: 'campaign-drakkenheim',
    name: 'Endra Jansen',
    aliases: ['Эндра Дженсен'],
    status: 'alive',
    gender: 'female',
    age: 27,
    species: 'Human',
    speciesId: 'species-human',
    description:
      'Из группы Рикарда Воса и Людвика вон Графа. Выжила после превращения Рикарда в монстра.',
    locations: ['Road to Emberwood'],
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-09-01T00:00:00Z',
  },

  {
    id: 'npc-rikard-vos',
    campaignId: 'campaign-drakkenheim',
    name: 'Rikard Vos',
    aliases: ['Рикард Восс'],
    status: 'dead',
    gender: 'male',
    age: 31,
    species: 'Human',
    speciesId: 'species-human',
    description:
      'Первый монстр, которого встретила партия. Потрогал делириум на дороге и начал превращаться в монстра — ночью трансформировался окончательно. Из группы Людвика вон Графа и Эндры Дженсен.',
    locations: ['Road to Emberwood'],
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-09-01T00:00:00Z',
  },

  {
    id: 'npc-ludwig',
    campaignId: 'campaign-drakkenheim',
    name: 'Ludwig von Graff',
    aliases: ['Людвик вон Граф'],
    status: 'dead',
    gender: 'male',
    age: 34,
    species: 'Human',
    speciesId: 'species-human',
    description: 'Из группы Рикарда Воса и Эндры Дженсен. Погиб на Дороге к Эмбервуду.',
    locations: ['Road to Emberwood'],
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-09-01T00:00:00Z',
  },

  {
    id: 'npc-kosta-stavros',
    campaignId: 'campaign-drakkenheim',
    name: 'Kosta Stavros',
    aliases: ['Костос Старвос'],
    status: 'dead',
    gender: 'male',
    age: 51,
    species: 'Human',
    speciesId: 'species-human',
    description:
      'Бывший владелец Red Lion Hotel. Убит допельгангером — подтверждено. В сессии 11 обнаружено, что он труп.',
    gmNotes: 'Допельгангер занял его место — кто-то ещё может быть заменён?',
    locations: ['Red Lion Hotel'],
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-11-01T00:00:00Z',
  },

  {
    id: 'npc-bogdan',
    campaignId: 'campaign-drakkenheim',
    name: 'Bogdan',
    aliases: ['Богдан'],
    status: 'missing',
    gender: 'male',
    age: 40,
    species: 'Human',
    speciesId: 'species-human',
    description:
      'Глава шайки, которая напала на партию в сессии 1. Сбежал во время встречи с монстром на дороге — забрал у кого-то кинжал. Где-то скрывается.',
    gmNotes: 'У кого кинжал? Что планирует?',
    locations: ['Road to Emberwood'],
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-09-01T00:00:00Z',
  },

  {
    id: 'npc-mind-reaper',
    campaignId: 'campaign-drakkenheim',
    name: 'Mind Reaper',
    aliases: ['Крадущий Мысли', 'Допельгангер', 'Зоя (ложная)'],
    status: 'missing',
    gender: 'nonbinary',
    species: 'Doppelganger',
    description:
      'Допельгангер. Выдавал себя за Зою в Прогнутом ряду. Спугнут малой иллюзией — сбежал (сессия 17). Зачем притворялся Зоей? Связан ли с фракциями?',
    gmNotes: 'Кто его контролирует? Цель — похитить лечение от делириума?',
    locations: ['Bent Row'],
    groupMemberships: [],
    createdAt: '2026-03-16T00:00:00Z',
    updatedAt: '2026-03-16T00:00:00Z',
  },

  {
    id: 'npc-chertyaka',
    campaignId: 'campaign-drakkenheim',
    name: 'Чертяка',
    aliases: ['Chertyaka', 'Черт'],
    status: 'missing',
    gender: 'male',
    age: 7,
    species: 'Horse',
    description:
      'Конь Сая. С партией с первой сессии. Долго не приручался, но потеплел после часовни. Почти наверняка заражён дымкой Дракенхейма — долгое время провёл в/около города. В сессии 17 отпущен на север от Прогнутого ряда перед побегом. Местонахождение неизвестно.',
    gmNotes: '⚠️ Вероятно заражён делириумом. Что с ним будет? Мутирует?',
    locations: ['Emberwood Village'],
    groupMemberships: [],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2026-03-16T00:00:00Z',
  },
];
